name: Docker build and push

on:
  workflow_dispatch:

permissions:
  # Does not modify or write to any resources, only allows workflow to request (fetch) & use (set) OIDC token
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.3.1
        with:
          role-to-assume: arn:aws:iam::${{ secrets.ACCOUNT_ID }}:role/GitHubActions-ECR-Push
          aws-region: eu-west-2

      - name: test
        run: |
          aws sts get-caller-identity
